server:
  port: 8080
  servlet:
    context-path: /oauth2-server
spring:
  application:
    name: oauth2-server
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://micheal.wang:3306/oauth2?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: mingkai13
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  # redis
  redis:
    host: www.micheal.wang
    port: 26379
    password: micheal13
    lettuce:
      pool:
        max-active: 32
        max-wait: -1
        min-idle: 0
    timeout: 120
    database: 2
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.security.oauth2server.domain
security:
  tokenStore:
    jwtTokenStoreEnable: true
    redisTokenStoreEnable: false
  login:
    loginPage: /loginUp.html
    loginSuccessUrl: /loginSuccess.html
    loginErrorUrl: /loginError.html
    loginUrl: /login
    rememberMeSeconds: 3600

