security:
  oauth2:
    client:
      client-id: app-a
      client-secret: secret
      user-authorization-uri: http://localhost:8080/oauth2-server/oauth/authorize
      access-token-uri: http://localhost:8080/oauth2-server/oauth/token
    resource:
      jwt:
        key-uri: http://localhost:8080/oauth2-server/oauth/token_key
server:
  port: 9090
  servlet:
    context-path: /app1
