spring:
  datasource:
    master:
      jdbc-url: jdbc:mysql://www.micheal.wang:33067/micheal-blog
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
    slave1:
      jdbc-url: jdbc:mysql://www.micheal.wang:33068/micheal-blog
      username: root   # ÷ª∂¡’Àªß
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml