server:
  port: 8081
spring:
  rabbitmq:
    virtual-host: /
    username: admin
    password: admin
    port: 5672
    host: 49.234.52.233
    listener:
      simple:
        acknowledge-mode: manual # 手动确认
        prefetch: 100