server:
  port: 8080
spring:
  redis:
    host: 10.0.12.201
    port: 6379
    password: 123456
    lettuce:
      pool:
        max-active: 32
        max-wait: -1
        min-idle: 0
    timeout: 120
    database: 0