server:
  port: 8080
security:
  login:
    loginPage: /loginUp.html
    loginSuccessUrl: /loginSuccess.html
    loginErrorUrl: /loginError.html
    loginUrl: /loginUp
    rememberMeSeconds: 3600
spring:
  datasource:
    url: jdbc:mysql://micheal.wang:3306/test?characterEncoding=utf-8&useSSL=false
    username: root
    password: mingkai13
    driver-class-name: com.mysql.jdbc.Driver