spring:
  application:
    name: mqtt-consumer
  #MQTT配置信息
  mqtt:
    #MQTT服务端地址，1883，如果有多个，用逗号隔开
    url: tcp://127.0.0.1:1883
    #用户名
    username: admin
    #密码
    password: public
    #客户端id（不能重复）
    clientId: producer-id
    #MQTT默认的消息推送主题，实际可在调用接口时指定
    defaultTopic: testtopic/data
    timeout: 10
    keepalive: 20
server:
  port: 8085